# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.32
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cloudglue.sdk.models.collection_moments_list_moments_inner import CollectionMomentsListMomentsInner
from typing import Optional, Set
from typing_extensions import Self

class CollectionMomentsList(BaseModel):
    """
    CollectionMomentsList
    """ # noqa: E501
    moments: List[CollectionMomentsListMomentsInner]
    total: StrictInt = Field(description="Exact total across current members.")
    next_cursor: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["moments", "total", "next_cursor"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CollectionMomentsList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in moments (list)
        _items = []
        if self.moments:
            for _item_moments in self.moments:
                if _item_moments:
                    _items.append(_item_moments.to_dict())
            _dict['moments'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CollectionMomentsList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "moments": [CollectionMomentsListMomentsInner.from_dict(_item) for _item in obj["moments"]] if obj.get("moments") is not None else None,
            "total": obj.get("total"),
            "next_cursor": obj.get("next_cursor")
        })
        return _obj


