# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.23
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from cloudglue.sdk.models.criterion_score import CriterionScore
from cloudglue.sdk.models.moment_evidence import MomentEvidence
from typing import Optional, Set
from typing_extensions import Self

class CollectionMomentsListMomentsInner(BaseModel):
    """
    CollectionMomentsListMomentsInner
    """ # noqa: E501
    moment_id: StrictStr
    start_time: Union[StrictFloat, StrictInt] = Field(description="Seconds from source start.")
    end_time: Union[StrictFloat, StrictInt]
    anchors: Optional[Dict[str, Union[StrictFloat, StrictInt]]] = Field(default=None, description="Declared anchors only; an anchor that was not found is absent, never null.")
    title: StrictStr
    reason: StrictStr
    speakers: Optional[List[StrictStr]] = None
    criterion_score: Optional[CriterionScore] = None
    rank_score: Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]] = Field(description="Normalized ordering within the run; what the default sort uses.")
    properties: Optional[Dict[str, Any]] = Field(default=None, description="Validates against the criterion's moment_schema.")
    evidence: Optional[MomentEvidence] = None
    file_id: StrictStr
    job_id: StrictStr
    criterion_name: StrictStr
    __properties: ClassVar[List[str]] = ["moment_id", "start_time", "end_time", "anchors", "title", "reason", "speakers", "criterion_score", "rank_score", "properties", "evidence", "file_id", "job_id", "criterion_name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CollectionMomentsListMomentsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of criterion_score
        if self.criterion_score:
            _dict['criterion_score'] = self.criterion_score.to_dict()
        # override the default output from pydantic by calling `to_dict()` of evidence
        if self.evidence:
            _dict['evidence'] = self.evidence.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CollectionMomentsListMomentsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "moment_id": obj.get("moment_id"),
            "start_time": obj.get("start_time"),
            "end_time": obj.get("end_time"),
            "anchors": obj.get("anchors"),
            "title": obj.get("title"),
            "reason": obj.get("reason"),
            "speakers": obj.get("speakers"),
            "criterion_score": CriterionScore.from_dict(obj["criterion_score"]) if obj.get("criterion_score") is not None else None,
            "rank_score": obj.get("rank_score"),
            "properties": obj.get("properties"),
            "evidence": MomentEvidence.from_dict(obj["evidence"]) if obj.get("evidence") is not None else None,
            "file_id": obj.get("file_id"),
            "job_id": obj.get("job_id"),
            "criterion_name": obj.get("criterion_name")
        })
        return _obj


