# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cloudglue.sdk.models.create_deep_search_request_knowledge_base import CreateDeepSearchRequestKnowledgeBase
from typing import Optional, Set
from typing_extensions import Self

class CreateDeepSearchRequest(BaseModel):
    """
    CreateDeepSearchRequest
    """ # noqa: E501
    knowledge_base: CreateDeepSearchRequestKnowledgeBase
    query: Annotated[str, Field(min_length=1, strict=True)] = Field(description="The search query.")
    scope: Optional[StrictStr] = Field(default='segment', description="The scope of results to return. 'segment' returns individual segments, 'file' returns file-level results.")
    limit: Optional[Annotated[int, Field(le=500, strict=True, ge=1)]] = Field(default=20, description="Maximum number of results to return. Actual count may be lower when exclude_weak_results is enabled.")
    exclude_weak_results: Optional[StrictBool] = Field(default=False, description="When true, removes results tagged as weak matches by the synthesis LLM.")
    include: Optional[List[StrictStr]] = Field(default=None, description="Additional fields to include in the response. 'search_queries' includes the intermediate search query plan.")
    stream: Optional[StrictBool] = Field(default=False, description="Stream the response via SSE. Mutually exclusive with background.")
    background: Optional[StrictBool] = Field(default=False, description="Process in the background. Returns immediately with status 'in_progress'. Mutually exclusive with stream.")
    __properties: ClassVar[List[str]] = ["knowledge_base", "query", "scope", "limit", "exclude_weak_results", "include", "stream", "background"]

    @field_validator('scope')
    def scope_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['segment', 'file']):
            raise ValueError("must be one of enum values ('segment', 'file')")
        return value

    @field_validator('include')
    def include_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['search_queries']):
                raise ValueError("each list item must be one of ('search_queries')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateDeepSearchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of knowledge_base
        if self.knowledge_base:
            _dict['knowledge_base'] = self.knowledge_base.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateDeepSearchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "knowledge_base": CreateDeepSearchRequestKnowledgeBase.from_dict(obj["knowledge_base"]) if obj.get("knowledge_base") is not None else None,
            "query": obj.get("query"),
            "scope": obj.get("scope") if obj.get("scope") is not None else 'segment',
            "limit": obj.get("limit") if obj.get("limit") is not None else 20,
            "exclude_weak_results": obj.get("exclude_weak_results") if obj.get("exclude_weak_results") is not None else False,
            "include": obj.get("include"),
            "stream": obj.get("stream") if obj.get("stream") is not None else False,
            "background": obj.get("background") if obj.get("background") is not None else False
        })
        return _obj


