# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.23
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cloudglue.sdk.models.metadata_import_filter_set import MetadataImportFilterSet
from typing import Optional, Set
from typing_extensions import Self

class CreateMetadataImportRequest(BaseModel):
    """
    CreateMetadataImportRequest
    """ # noqa: E501
    name: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="Display name for the import")
    connector_id: StrictStr = Field(description="Data connector to list files from. Supported types: google-drive, dropbox, zoom, gong, recall, grain, iconik.")
    filters: Optional[Annotated[List[MetadataImportFilterSet], Field(max_length=20)]] = Field(default=None, description="Listing passes; empty (the default) means one unfiltered pass")
    default_mode: Optional[StrictStr] = Field(default='append', description="Mode used when a run does not specify one. append imports new files and retries previously-failed ones; refresh re-imports everything the filters match.")
    delete_missing: Optional[StrictBool] = Field(default=False, description="On refresh runs, remove files this import previously brought in that the source no longer returns. Only files imported by this import are ever removed — manually-added files and other imports are untouched.")
    rate_limit: Optional[Annotated[int, Field(le=50, strict=True, ge=1)]] = Field(default=None, description="Upstream list requests per second. Defaults to a per-connector safe rate (e.g. gong 2, zoom 6, google-drive/dropbox 8) and is clamped to a per-connector ceiling (gong 3, iconik 12, zoom/grain/recall 10, google-drive/dropbox 20) sized to keep the whole account inside each provider's published rate budget.")
    start: Optional[StrictBool] = Field(default=True, description="Trigger the first run immediately. false saves the definition only.")
    max_files: Optional[Annotated[int, Field(le=1000000, strict=True, ge=1)]] = Field(default=None, description="Stop each run after processing this many files from the listing. A capped run stops listing at the limit and never runs the delete-missing sweep — a truncated listing is incomplete by definition, so nothing is removed based on it. Media imports additionally cap every run at 10,000 files, whatever this is set to.")
    include_thumbnails: Optional[StrictBool] = Field(default=False, description="Copy connector poster images as default thumbnails for imported files, for sources that provide one (Grain, iconik, Google Drive, and Dropbox today). Off by default. Posters are copied in the background, so they do not slow the import itself and may appear shortly after a file is indexed. Metadata imports only — setting it on a media import is a 400, since imported media gets real thumbnails from the processing pipeline.")
    enrich_metadata: Optional[StrictBool] = Field(default=False, description="Backfill source-metadata fields the connector's list endpoint omits, after each index batch settles: Gong parties + Call Spotlight content (batched - enriched docs are re-embedded so the content is searchable) and Dropbox media_info duration/dimensions (per-file). No-op for other connectors. Off by default: it spends upstream API budget and, for Gong, embedding work. Metadata imports only — setting it on a media import is a 400, since a media run ingests each file in full and has no metadata-only record to enrich.")
    __properties: ClassVar[List[str]] = ["name", "connector_id", "filters", "default_mode", "delete_missing", "rate_limit", "start", "max_files", "include_thumbnails", "enrich_metadata"]

    @field_validator('default_mode')
    def default_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['append', 'refresh']):
            raise ValueError("must be one of enum values ('append', 'refresh')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateMetadataImportRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in filters (list)
        _items = []
        if self.filters:
            for _item_filters in self.filters:
                if _item_filters:
                    _items.append(_item_filters.to_dict())
            _dict['filters'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateMetadataImportRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "connector_id": obj.get("connector_id"),
            "filters": [MetadataImportFilterSet.from_dict(_item) for _item in obj["filters"]] if obj.get("filters") is not None else None,
            "default_mode": obj.get("default_mode") if obj.get("default_mode") is not None else 'append',
            "delete_missing": obj.get("delete_missing") if obj.get("delete_missing") is not None else False,
            "rate_limit": obj.get("rate_limit"),
            "start": obj.get("start") if obj.get("start") is not None else True,
            "max_files": obj.get("max_files"),
            "include_thumbnails": obj.get("include_thumbnails") if obj.get("include_thumbnails") is not None else False,
            "enrich_metadata": obj.get("enrich_metadata") if obj.get("enrich_metadata") is not None else False
        })
        return _obj


