# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from cloudglue.sdk.models.deep_search_usage import DeepSearchUsage
from typing import Optional, Set
from typing_extensions import Self

class DeepSearchListItem(BaseModel):
    """
    DeepSearchListItem
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Deep search ID")
    object: Optional[StrictStr] = Field(default=None, description="Object type identifier")
    status: Optional[StrictStr] = Field(default=None, description="Current status")
    created_at: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Unix timestamp of creation")
    query: Optional[StrictStr] = Field(default=None, description="The original search query")
    scope: Optional[StrictStr] = Field(default=None, description="Search scope")
    total: Optional[StrictInt] = Field(default=None, description="Total number of results")
    usage: Optional[DeepSearchUsage] = None
    __properties: ClassVar[List[str]] = ["id", "object", "status", "created_at", "query", "scope", "total", "usage"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['deep_search']):
            raise ValueError("must be one of enum values ('deep_search')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['in_progress', 'completed', 'failed', 'cancelled']):
            raise ValueError("must be one of enum values ('in_progress', 'completed', 'failed', 'cancelled')")
        return value

    @field_validator('scope')
    def scope_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['segment', 'file']):
            raise ValueError("must be one of enum values ('segment', 'file')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeepSearchListItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeepSearchListItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "query": obj.get("query"),
            "scope": obj.get("scope"),
            "total": obj.get("total"),
            "usage": DeepSearchUsage.from_dict(obj["usage"]) if obj.get("usage") is not None else None
        })
        return _obj


