# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.6.8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from cloudglue.sdk.models.deep_search_error import DeepSearchError
from cloudglue.sdk.models.deep_search_result import DeepSearchResult
from cloudglue.sdk.models.deep_search_search_query_plan import DeepSearchSearchQueryPlan
from cloudglue.sdk.models.deep_search_usage import DeepSearchUsage
from typing import Optional, Set
from typing_extensions import Self

class DeepSearch(BaseModel):
    """
    DeepSearch
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Deep search ID")
    object: Optional[StrictStr] = Field(default=None, description="Object type identifier")
    status: Optional[StrictStr] = Field(default=None, description="Current status of the deep search")
    created_at: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Unix timestamp of when the deep search was created")
    query: Optional[StrictStr] = Field(default=None, description="The original search query")
    scope: Optional[StrictStr] = Field(default=None, description="The scope of the search results")
    text: Optional[StrictStr] = Field(default=None, description="LLM-generated synthesis text summarizing the results")
    results: Optional[List[DeepSearchResult]] = Field(default=None, description="Array of search results")
    total: Optional[StrictInt] = Field(default=None, description="Total number of results")
    limit: Optional[StrictInt] = Field(default=None, description="Maximum number of results requested")
    search_queries: Optional[List[DeepSearchSearchQueryPlan]] = Field(default=None, description="Intermediate search query plans (included when requested via include=['search_queries'])")
    usage: Optional[DeepSearchUsage] = None
    error: Optional[DeepSearchError] = None
    __properties: ClassVar[List[str]] = ["id", "object", "status", "created_at", "query", "scope", "text", "results", "total", "limit", "search_queries", "usage", "error"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['deep_search']):
            raise ValueError("must be one of enum values ('deep_search')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['in_progress', 'completed', 'failed', 'cancelled']):
            raise ValueError("must be one of enum values ('in_progress', 'completed', 'failed', 'cancelled')")
        return value

    @field_validator('scope')
    def scope_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['segment', 'file']):
            raise ValueError("must be one of enum values ('segment', 'file')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeepSearch from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in results (list)
        _items = []
        if self.results:
            for _item_results in self.results:
                if _item_results:
                    _items.append(_item_results.to_dict())
            _dict['results'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in search_queries (list)
        _items = []
        if self.search_queries:
            for _item_search_queries in self.search_queries:
                if _item_search_queries:
                    _items.append(_item_search_queries.to_dict())
            _dict['search_queries'] = _items
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        # set to None if text (nullable) is None
        # and model_fields_set contains the field
        if self.text is None and "text" in self.model_fields_set:
            _dict['text'] = None

        # set to None if results (nullable) is None
        # and model_fields_set contains the field
        if self.results is None and "results" in self.model_fields_set:
            _dict['results'] = None

        # set to None if search_queries (nullable) is None
        # and model_fields_set contains the field
        if self.search_queries is None and "search_queries" in self.model_fields_set:
            _dict['search_queries'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeepSearch from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "object": obj.get("object"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "query": obj.get("query"),
            "scope": obj.get("scope"),
            "text": obj.get("text"),
            "results": [DeepSearchResult.from_dict(_item) for _item in obj["results"]] if obj.get("results") is not None else None,
            "total": obj.get("total"),
            "limit": obj.get("limit"),
            "search_queries": [DeepSearchSearchQueryPlan.from_dict(_item) for _item in obj["search_queries"]] if obj.get("search_queries") is not None else None,
            "usage": DeepSearchUsage.from_dict(obj["usage"]) if obj.get("usage") is not None else None,
            "error": DeepSearchError.from_dict(obj["error"]) if obj.get("error") is not None else None
        })
        return _obj


