# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.6.7
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from cloudglue.sdk.models.describe_data import DescribeData
from cloudglue.sdk.models.describe_describe_config import DescribeDescribeConfig
from cloudglue.sdk.models.extract_chapters_inner import ExtractChaptersInner
from cloudglue.sdk.models.extract_shots_inner import ExtractShotsInner
from typing import Optional, Set
from typing_extensions import Self

class Describe(BaseModel):
    """
    Describe
    """ # noqa: E501
    job_id: StrictStr
    status: StrictStr
    url: Optional[StrictStr] = Field(default=None, description="The URL of the processed video")
    duration_seconds: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Duration of the video in seconds")
    thumbnail_url: Optional[StrictStr] = Field(default=None, description="URL of the file-level thumbnail for the video. Only present when include_thumbnails=true.")
    created_at: Optional[StrictInt] = Field(default=None, description="Unix timestamp in milliseconds when the job was created")
    describe_config: Optional[DescribeDescribeConfig] = None
    use_in_default_index: Optional[StrictBool] = Field(default=None, description="Whether this describe job's search documents are included in the default index.")
    data: Optional[DescribeData] = None
    error: Optional[StrictStr] = Field(default=None, description="Error message if status is 'failed'")
    segmentation_id: Optional[StrictStr] = Field(default=None, description="The ID of the segmentation job if the describe was run with a segmentation")
    chapters: Optional[List[ExtractChaptersInner]] = Field(default=None, description="Array of narrative chapters (only present when include_chapters=true and segmentation strategy is 'narrative')")
    shots: Optional[List[ExtractShotsInner]] = Field(default=None, description="Array of shot boundaries (only present when include_shots=true and segmentation strategy is 'shot-detector')")
    total_chapters: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Total number of chapters (only present when include_chapters=true and segmentation strategy is 'narrative')")
    total_shots: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Total number of shots (only present when include_shots=true and segmentation strategy is 'shot-detector')")
    __properties: ClassVar[List[str]] = ["job_id", "status", "url", "duration_seconds", "thumbnail_url", "created_at", "describe_config", "use_in_default_index", "data", "error", "segmentation_id", "chapters", "shots", "total_chapters", "total_shots"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'processing', 'completed', 'failed', 'not_applicable']):
            raise ValueError("must be one of enum values ('pending', 'processing', 'completed', 'failed', 'not_applicable')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Describe from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of describe_config
        if self.describe_config:
            _dict['describe_config'] = self.describe_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in chapters (list)
        _items = []
        if self.chapters:
            for _item_chapters in self.chapters:
                if _item_chapters:
                    _items.append(_item_chapters.to_dict())
            _dict['chapters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in shots (list)
        _items = []
        if self.shots:
            for _item_shots in self.shots:
                if _item_shots:
                    _items.append(_item_shots.to_dict())
            _dict['shots'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Describe from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "job_id": obj.get("job_id"),
            "status": obj.get("status"),
            "url": obj.get("url"),
            "duration_seconds": obj.get("duration_seconds"),
            "thumbnail_url": obj.get("thumbnail_url"),
            "created_at": obj.get("created_at"),
            "describe_config": DescribeDescribeConfig.from_dict(obj["describe_config"]) if obj.get("describe_config") is not None else None,
            "use_in_default_index": obj.get("use_in_default_index"),
            "data": DescribeData.from_dict(obj["data"]) if obj.get("data") is not None else None,
            "error": obj.get("error"),
            "segmentation_id": obj.get("segmentation_id"),
            "chapters": [ExtractChaptersInner.from_dict(_item) for _item in obj["chapters"]] if obj.get("chapters") is not None else None,
            "shots": [ExtractShotsInner.from_dict(_item) for _item in obj["shots"]] if obj.get("shots") is not None else None,
            "total_chapters": obj.get("total_chapters"),
            "total_shots": obj.get("total_shots")
        })
        return _obj


