# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from cloudglue.sdk.models.moment_criterion import MomentCriterion
from typing import Optional, Set
from typing_extensions import Self

class FindMomentsFindMomentsConfig(BaseModel):
    """
    Echo of the request as the run resolved it, plus criterion_hash, the resolved describe_job_id, and the engine version. Defaults the request omitted are filled in here.
    """ # noqa: E501
    criterion: Optional[MomentCriterion] = None
    criterion_hash: Optional[StrictStr] = Field(default=None, description="Stable hash of the snapshotted criterion; identical criteria share a hash.")
    describe_job_id: Optional[StrictStr] = Field(default=None, description="The describe the run actually used, whether reused, pinned, or created internally.")
    signals_required: Optional[List[StrictStr]] = None
    boundary_policy: Optional[StrictStr] = None
    speaker_filter: Optional[Dict[str, Any]] = Field(default=None, description="Speaker restriction, present when the request set one.")
    min_duration_seconds: Optional[Union[StrictFloat, StrictInt]] = None
    max_duration_seconds: Optional[Union[StrictFloat, StrictInt]] = None
    cache_policy: Optional[StrictStr] = None
    engine_version: Optional[StrictInt] = Field(default=None, description="Version of the moment-discovery engine that produced the run.")
    __properties: ClassVar[List[str]] = ["criterion", "criterion_hash", "describe_job_id", "signals_required", "boundary_policy", "speaker_filter", "min_duration_seconds", "max_duration_seconds", "cache_policy", "engine_version"]

    @field_validator('boundary_policy')
    def boundary_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['sentence', 'tight', 'loose']):
            raise ValueError("must be one of enum values ('sentence', 'tight', 'loose')")
        return value

    @field_validator('cache_policy')
    def cache_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['reuse', 'refresh']):
            raise ValueError("must be one of enum values ('reuse', 'refresh')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FindMomentsFindMomentsConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of criterion
        if self.criterion:
            _dict['criterion'] = self.criterion.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FindMomentsFindMomentsConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "criterion": MomentCriterion.from_dict(obj["criterion"]) if obj.get("criterion") is not None else None,
            "criterion_hash": obj.get("criterion_hash"),
            "describe_job_id": obj.get("describe_job_id"),
            "signals_required": obj.get("signals_required"),
            "boundary_policy": obj.get("boundary_policy"),
            "speaker_filter": obj.get("speaker_filter"),
            "min_duration_seconds": obj.get("min_duration_seconds"),
            "max_duration_seconds": obj.get("max_duration_seconds"),
            "cache_policy": obj.get("cache_policy"),
            "engine_version": obj.get("engine_version")
        })
        return _obj


