# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.23
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from cloudglue.sdk.models.find_moments_find_moments_config import FindMomentsFindMomentsConfig
from cloudglue.sdk.models.moment import Moment
from cloudglue.sdk.models.moment_finding import MomentFinding
from typing import Optional, Set
from typing_extensions import Self

class FindMoments(BaseModel):
    """
    FindMoments
    """ # noqa: E501
    job_id: StrictStr
    status: StrictStr
    created_at: StrictInt = Field(description="Unix timestamp in milliseconds when the run was created")
    url: StrictStr
    find_moments_config: Optional[FindMomentsFindMomentsConfig] = None
    moments: Optional[List[Moment]] = None
    findings: Optional[List[MomentFinding]] = None
    total_moments: Optional[StrictInt] = Field(default=None, description="Full accepted count, independent of the limit read parameter.")
    error: Optional[StrictStr] = Field(default=None, description="Curated failure message, present on failed runs.")
    __properties: ClassVar[List[str]] = ["job_id", "status", "created_at", "url", "find_moments_config", "moments", "findings", "total_moments", "error"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'processing', 'completed', 'failed', 'cancelled']):
            raise ValueError("must be one of enum values ('pending', 'processing', 'completed', 'failed', 'cancelled')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FindMoments from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of find_moments_config
        if self.find_moments_config:
            _dict['find_moments_config'] = self.find_moments_config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in moments (list)
        _items = []
        if self.moments:
            for _item_moments in self.moments:
                if _item_moments:
                    _items.append(_item_moments.to_dict())
            _dict['moments'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in findings (list)
        _items = []
        if self.findings:
            for _item_findings in self.findings:
                if _item_findings:
                    _items.append(_item_findings.to_dict())
            _dict['findings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FindMoments from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "job_id": obj.get("job_id"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "url": obj.get("url"),
            "find_moments_config": FindMomentsFindMomentsConfig.from_dict(obj["find_moments_config"]) if obj.get("find_moments_config") is not None else None,
            "moments": [Moment.from_dict(_item) for _item in obj["moments"]] if obj.get("moments") is not None else None,
            "findings": [MomentFinding.from_dict(_item) for _item in obj["findings"]] if obj.get("findings") is not None else None,
            "total_moments": obj.get("total_moments"),
            "error": obj.get("error")
        })
        return _obj


