# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.10
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from cloudglue.sdk.models.gong_source_metadata_parties_inner import GongSourceMetadataPartiesInner
from cloudglue.sdk.models.gong_source_metadata_topics_inner import GongSourceMetadataTopicsInner
from cloudglue.sdk.models.gong_source_metadata_trackers_inner import GongSourceMetadataTrackersInner
from typing import Optional, Set
from typing_extensions import Self

class GongSourceMetadata(BaseModel):
    """
    Source provenance captured from Gong at ingest time. Signed media URLs are never included. AI content fields (topics, trackers, brief, key_points) require Gong Call Spotlight entitlement and are only captured at sync/lookup time.
    """ # noqa: E501
    source_type: StrictStr = Field(description="Discriminator identifying the upstream connector.")
    gong_call_id: StrictStr = Field(description="Gong call id.")
    title: Optional[StrictStr] = Field(default=None, description="Call title (empty string when Gong omits it).")
    started: Optional[StrictStr] = Field(default=None, description="UTC time the call started.")
    scheduled: Optional[StrictStr] = Field(default=None, description="UTC time the call was scheduled for.")
    duration: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Call duration in seconds.")
    gong_url: Optional[StrictStr] = Field(default=None, description="URL to the call in Gong.")
    meeting_url: Optional[StrictStr] = Field(default=None, description="URL of the underlying meeting.")
    is_private: Optional[StrictBool] = Field(default=None, description="Whether the call is private in Gong. Private calls cannot be listed or synced.")
    purpose: Optional[StrictStr] = None
    primary_user_id: Optional[StrictStr] = Field(default=None, description="Gong user id of the call owner.")
    direction: Optional[StrictStr] = Field(default=None, description="Inbound, Outbound, Conference, or Unknown.")
    system: Optional[StrictStr] = Field(default=None, description="Telephony/meeting system the call was held on.")
    scope: Optional[StrictStr] = Field(default=None, description="Internal, External, or Unknown.")
    language: Optional[StrictStr] = Field(default=None, description="ISO-639-2B language code Gong detected.")
    workspace_id: Optional[StrictStr] = Field(default=None, description="Gong workspace id.")
    call_media_type: Optional[StrictStr] = Field(default=None, description="Gong's media indicator: Video or Audio.")
    parties: Optional[List[GongSourceMetadataPartiesInner]] = Field(default=None, description="Call participants.")
    topics: Optional[List[GongSourceMetadataTopicsInner]] = Field(default=None, description="AI topics (Call Spotlight).")
    trackers: Optional[List[GongSourceMetadataTrackersInner]] = Field(default=None, description="Tracker keyword hit counts (Call Spotlight).")
    brief: Optional[StrictStr] = Field(default=None, description="AI call brief (Call Spotlight).")
    key_points: Optional[List[StrictStr]] = Field(default=None, description="AI key points (Call Spotlight).")
    __properties: ClassVar[List[str]] = ["source_type", "gong_call_id", "title", "started", "scheduled", "duration", "gong_url", "meeting_url", "is_private", "purpose", "primary_user_id", "direction", "system", "scope", "language", "workspace_id", "call_media_type", "parties", "topics", "trackers", "brief", "key_points"]

    @field_validator('source_type')
    def source_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['gong']):
            raise ValueError("must be one of enum values ('gong')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GongSourceMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in parties (list)
        _items = []
        if self.parties:
            for _item_parties in self.parties:
                if _item_parties:
                    _items.append(_item_parties.to_dict())
            _dict['parties'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in topics (list)
        _items = []
        if self.topics:
            for _item_topics in self.topics:
                if _item_topics:
                    _items.append(_item_topics.to_dict())
            _dict['topics'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in trackers (list)
        _items = []
        if self.trackers:
            for _item_trackers in self.trackers:
                if _item_trackers:
                    _items.append(_item_trackers.to_dict())
            _dict['trackers'] = _items
        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if started (nullable) is None
        # and model_fields_set contains the field
        if self.started is None and "started" in self.model_fields_set:
            _dict['started'] = None

        # set to None if scheduled (nullable) is None
        # and model_fields_set contains the field
        if self.scheduled is None and "scheduled" in self.model_fields_set:
            _dict['scheduled'] = None

        # set to None if duration (nullable) is None
        # and model_fields_set contains the field
        if self.duration is None and "duration" in self.model_fields_set:
            _dict['duration'] = None

        # set to None if gong_url (nullable) is None
        # and model_fields_set contains the field
        if self.gong_url is None and "gong_url" in self.model_fields_set:
            _dict['gong_url'] = None

        # set to None if meeting_url (nullable) is None
        # and model_fields_set contains the field
        if self.meeting_url is None and "meeting_url" in self.model_fields_set:
            _dict['meeting_url'] = None

        # set to None if is_private (nullable) is None
        # and model_fields_set contains the field
        if self.is_private is None and "is_private" in self.model_fields_set:
            _dict['is_private'] = None

        # set to None if purpose (nullable) is None
        # and model_fields_set contains the field
        if self.purpose is None and "purpose" in self.model_fields_set:
            _dict['purpose'] = None

        # set to None if primary_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.primary_user_id is None and "primary_user_id" in self.model_fields_set:
            _dict['primary_user_id'] = None

        # set to None if direction (nullable) is None
        # and model_fields_set contains the field
        if self.direction is None and "direction" in self.model_fields_set:
            _dict['direction'] = None

        # set to None if system (nullable) is None
        # and model_fields_set contains the field
        if self.system is None and "system" in self.model_fields_set:
            _dict['system'] = None

        # set to None if scope (nullable) is None
        # and model_fields_set contains the field
        if self.scope is None and "scope" in self.model_fields_set:
            _dict['scope'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if workspace_id (nullable) is None
        # and model_fields_set contains the field
        if self.workspace_id is None and "workspace_id" in self.model_fields_set:
            _dict['workspace_id'] = None

        # set to None if call_media_type (nullable) is None
        # and model_fields_set contains the field
        if self.call_media_type is None and "call_media_type" in self.model_fields_set:
            _dict['call_media_type'] = None

        # set to None if parties (nullable) is None
        # and model_fields_set contains the field
        if self.parties is None and "parties" in self.model_fields_set:
            _dict['parties'] = None

        # set to None if topics (nullable) is None
        # and model_fields_set contains the field
        if self.topics is None and "topics" in self.model_fields_set:
            _dict['topics'] = None

        # set to None if trackers (nullable) is None
        # and model_fields_set contains the field
        if self.trackers is None and "trackers" in self.model_fields_set:
            _dict['trackers'] = None

        # set to None if brief (nullable) is None
        # and model_fields_set contains the field
        if self.brief is None and "brief" in self.model_fields_set:
            _dict['brief'] = None

        # set to None if key_points (nullable) is None
        # and model_fields_set contains the field
        if self.key_points is None and "key_points" in self.model_fields_set:
            _dict['key_points'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GongSourceMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source_type": obj.get("source_type"),
            "gong_call_id": obj.get("gong_call_id"),
            "title": obj.get("title"),
            "started": obj.get("started"),
            "scheduled": obj.get("scheduled"),
            "duration": obj.get("duration"),
            "gong_url": obj.get("gong_url"),
            "meeting_url": obj.get("meeting_url"),
            "is_private": obj.get("is_private"),
            "purpose": obj.get("purpose"),
            "primary_user_id": obj.get("primary_user_id"),
            "direction": obj.get("direction"),
            "system": obj.get("system"),
            "scope": obj.get("scope"),
            "language": obj.get("language"),
            "workspace_id": obj.get("workspace_id"),
            "call_media_type": obj.get("call_media_type"),
            "parties": [GongSourceMetadataPartiesInner.from_dict(_item) for _item in obj["parties"]] if obj.get("parties") is not None else None,
            "topics": [GongSourceMetadataTopicsInner.from_dict(_item) for _item in obj["topics"]] if obj.get("topics") is not None else None,
            "trackers": [GongSourceMetadataTrackersInner.from_dict(_item) for _item in obj["trackers"]] if obj.get("trackers") is not None else None,
            "brief": obj.get("brief"),
            "key_points": obj.get("key_points")
        })
        return _obj


