# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.11
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class IconikSourceMetadata(BaseModel):
    """
    Source provenance captured from iconik at ingest time. Signed download URLs are never included.
    """ # noqa: E501
    source_type: StrictStr = Field(description="Discriminator identifying the upstream connector.")
    iconik_asset_id: StrictStr = Field(description="iconik asset id.")
    title: Optional[StrictStr] = Field(default=None, description="Asset title.")
    media_type: Optional[StrictStr] = Field(default=None, description="iconik media type of the asset (e.g. video, audio).")
    date_created: Optional[StrictStr] = Field(default=None, description="UTC time the asset was created in iconik.")
    date_modified: Optional[StrictStr] = Field(default=None, description="UTC time the asset was last modified in iconik.")
    duration_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Asset duration in milliseconds, when iconik reports one.")
    ingested_rendition: Optional[StrictStr] = Field(default=None, description="Which rendition Cloudglue downloaded: the web proxy (preferred) or the ORIGINAL file.")
    iconik_url: Optional[StrictStr] = Field(default=None, description="Deep link to the asset page in iconik.")
    external_id: Optional[StrictStr] = Field(default=None, description="External reference id set on the asset in iconik.")
    created_by_user: Optional[StrictStr] = Field(default=None, description="iconik user id that created the asset.")
    iconik_metadata: Optional[Dict[str, Any]] = Field(default=None, description="Custom metadata-view field values from iconik (customer-defined schemas, e.g. a screening view's UGC Title / Keywords / Categories), captured verbatim keyed by field name. Indexed into metadata-collection search documents and filterable via source_metadata.iconik_metadata.<FieldName> paths.")
    __properties: ClassVar[List[str]] = ["source_type", "iconik_asset_id", "title", "media_type", "date_created", "date_modified", "duration_ms", "ingested_rendition", "iconik_url", "external_id", "created_by_user", "iconik_metadata"]

    @field_validator('source_type')
    def source_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['iconik']):
            raise ValueError("must be one of enum values ('iconik')")
        return value

    @field_validator('ingested_rendition')
    def ingested_rendition_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['proxy', 'original']):
            raise ValueError("must be one of enum values ('proxy', 'original')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IconikSourceMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if media_type (nullable) is None
        # and model_fields_set contains the field
        if self.media_type is None and "media_type" in self.model_fields_set:
            _dict['media_type'] = None

        # set to None if date_created (nullable) is None
        # and model_fields_set contains the field
        if self.date_created is None and "date_created" in self.model_fields_set:
            _dict['date_created'] = None

        # set to None if date_modified (nullable) is None
        # and model_fields_set contains the field
        if self.date_modified is None and "date_modified" in self.model_fields_set:
            _dict['date_modified'] = None

        # set to None if duration_ms (nullable) is None
        # and model_fields_set contains the field
        if self.duration_ms is None and "duration_ms" in self.model_fields_set:
            _dict['duration_ms'] = None

        # set to None if ingested_rendition (nullable) is None
        # and model_fields_set contains the field
        if self.ingested_rendition is None and "ingested_rendition" in self.model_fields_set:
            _dict['ingested_rendition'] = None

        # set to None if iconik_url (nullable) is None
        # and model_fields_set contains the field
        if self.iconik_url is None and "iconik_url" in self.model_fields_set:
            _dict['iconik_url'] = None

        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict['external_id'] = None

        # set to None if created_by_user (nullable) is None
        # and model_fields_set contains the field
        if self.created_by_user is None and "created_by_user" in self.model_fields_set:
            _dict['created_by_user'] = None

        # set to None if iconik_metadata (nullable) is None
        # and model_fields_set contains the field
        if self.iconik_metadata is None and "iconik_metadata" in self.model_fields_set:
            _dict['iconik_metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IconikSourceMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source_type": obj.get("source_type"),
            "iconik_asset_id": obj.get("iconik_asset_id"),
            "title": obj.get("title"),
            "media_type": obj.get("media_type"),
            "date_created": obj.get("date_created"),
            "date_modified": obj.get("date_modified"),
            "duration_ms": obj.get("duration_ms"),
            "ingested_rendition": obj.get("ingested_rendition"),
            "iconik_url": obj.get("iconik_url"),
            "external_id": obj.get("external_id"),
            "created_by_user": obj.get("created_by_user"),
            "iconik_metadata": obj.get("iconik_metadata")
        })
        return _obj


