# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.6.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from cloudglue.sdk.models.describe_data_all_of_segment_summary_inner import DescribeDataAllOfSegmentSummaryInner
from cloudglue.sdk.models.describe_output_part import DescribeOutputPart
from cloudglue.sdk.models.extract_chapters_inner import ExtractChaptersInner
from cloudglue.sdk.models.extract_shots_inner import ExtractShotsInner
from cloudglue.sdk.models.speech_output_part import SpeechOutputPart
from typing import Optional, Set
from typing_extensions import Self

class MediaDescription(BaseModel):
    """
    MediaDescription
    """ # noqa: E501
    visual_scene_description: Optional[List[DescribeOutputPart]] = Field(default=None, description="Array of visual descriptions")
    scene_text: Optional[List[DescribeOutputPart]] = Field(default=None, description="Array of scene text extractions")
    speech: Optional[List[SpeechOutputPart]] = Field(default=None, description="Array of speech transcriptions")
    audio_description: Optional[List[DescribeOutputPart]] = Field(default=None, description="Array of audio descriptions")
    collection_id: StrictStr = Field(description="Unique identifier for the collection")
    file_id: StrictStr = Field(description="Unique identifier for the file")
    thumbnail_url: Optional[StrictStr] = Field(default=None, description="URL of the file-level thumbnail for the video. Only present when include_thumbnails=true.")
    content: Optional[StrictStr] = Field(default=None, description="Content string returned based on formatting, e.g. set to markdown text when response_format=markdown is requested")
    title: Optional[StrictStr] = Field(default=None, description="Generated title of the video")
    summary: Optional[StrictStr] = Field(default=None, description="Generated video level summary")
    duration_seconds: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Duration of the video in seconds")
    segment_summary: Optional[List[DescribeDataAllOfSegmentSummaryInner]] = Field(default=None, description="Array of summary information for each segment of the video")
    chapters: Optional[List[ExtractChaptersInner]] = Field(default=None, description="Array of narrative chapters (only present when include_chapters=true and segmentation strategy is 'narrative')")
    shots: Optional[List[ExtractShotsInner]] = Field(default=None, description="Array of shot boundaries (only present when include_shots=true and segmentation strategy is 'shot-detector')")
    total_chapters: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Total number of chapters (only present when include_chapters=true and segmentation strategy is 'narrative')")
    total_shots: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Total number of shots (only present when include_shots=true and segmentation strategy is 'shot-detector')")
    __properties: ClassVar[List[str]] = ["visual_scene_description", "scene_text", "speech", "audio_description", "collection_id", "file_id", "thumbnail_url", "content", "title", "summary", "duration_seconds", "segment_summary", "chapters", "shots", "total_chapters", "total_shots"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MediaDescription from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in visual_scene_description (list)
        _items = []
        if self.visual_scene_description:
            for _item_visual_scene_description in self.visual_scene_description:
                if _item_visual_scene_description:
                    _items.append(_item_visual_scene_description.to_dict())
            _dict['visual_scene_description'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in scene_text (list)
        _items = []
        if self.scene_text:
            for _item_scene_text in self.scene_text:
                if _item_scene_text:
                    _items.append(_item_scene_text.to_dict())
            _dict['scene_text'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in speech (list)
        _items = []
        if self.speech:
            for _item_speech in self.speech:
                if _item_speech:
                    _items.append(_item_speech.to_dict())
            _dict['speech'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in audio_description (list)
        _items = []
        if self.audio_description:
            for _item_audio_description in self.audio_description:
                if _item_audio_description:
                    _items.append(_item_audio_description.to_dict())
            _dict['audio_description'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in segment_summary (list)
        _items = []
        if self.segment_summary:
            for _item_segment_summary in self.segment_summary:
                if _item_segment_summary:
                    _items.append(_item_segment_summary.to_dict())
            _dict['segment_summary'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in chapters (list)
        _items = []
        if self.chapters:
            for _item_chapters in self.chapters:
                if _item_chapters:
                    _items.append(_item_chapters.to_dict())
            _dict['chapters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in shots (list)
        _items = []
        if self.shots:
            for _item_shots in self.shots:
                if _item_shots:
                    _items.append(_item_shots.to_dict())
            _dict['shots'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MediaDescription from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "visual_scene_description": [DescribeOutputPart.from_dict(_item) for _item in obj["visual_scene_description"]] if obj.get("visual_scene_description") is not None else None,
            "scene_text": [DescribeOutputPart.from_dict(_item) for _item in obj["scene_text"]] if obj.get("scene_text") is not None else None,
            "speech": [SpeechOutputPart.from_dict(_item) for _item in obj["speech"]] if obj.get("speech") is not None else None,
            "audio_description": [DescribeOutputPart.from_dict(_item) for _item in obj["audio_description"]] if obj.get("audio_description") is not None else None,
            "collection_id": obj.get("collection_id"),
            "file_id": obj.get("file_id"),
            "thumbnail_url": obj.get("thumbnail_url"),
            "content": obj.get("content"),
            "title": obj.get("title"),
            "summary": obj.get("summary"),
            "duration_seconds": obj.get("duration_seconds"),
            "segment_summary": [DescribeDataAllOfSegmentSummaryInner.from_dict(_item) for _item in obj["segment_summary"]] if obj.get("segment_summary") is not None else None,
            "chapters": [ExtractChaptersInner.from_dict(_item) for _item in obj["chapters"]] if obj.get("chapters") is not None else None,
            "shots": [ExtractShotsInner.from_dict(_item) for _item in obj["shots"]] if obj.get("shots") is not None else None,
            "total_chapters": obj.get("total_chapters"),
            "total_shots": obj.get("total_shots")
        })
        return _obj


