# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from cloudglue.sdk.models.metadata_import_run_progress import MetadataImportRunProgress
from typing import Optional, Set
from typing_extensions import Self

class MetadataImportRun(BaseModel):
    """
    One execution of a metadata import.
    """ # noqa: E501
    object: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    import_id: Optional[StrictStr] = None
    import_type: Optional[StrictStr] = Field(default=None, description="What this run ingests, inherited from the import definition: metadata indexes source metadata only (free); media ingests and processes the actual files (billed per file).")
    mode: Optional[StrictStr] = Field(default=None, description="append imports new files and retries previously-failed ones; refresh re-imports everything the filters match. For media imports, refresh re-syncs the source metadata of files it already imported — media bytes are never re-downloaded.")
    delete_missing: Optional[StrictBool] = Field(default=None, description="Whether this run sweeps files this import previously brought in that the source no longer returns (refresh runs only)")
    status: Optional[StrictStr] = None
    progress: Optional[MetadataImportRunProgress] = None
    error: Optional[StrictStr] = Field(default=None, description="User-facing failure reason when status is failed")
    started_at: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Unix timestamp in milliseconds")
    completed_at: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Unix timestamp in milliseconds")
    created_at: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Unix timestamp in milliseconds")
    max_files: Optional[StrictInt] = Field(default=None, description="The cap this run executed with; null means unbounded")
    include_thumbnails: Optional[StrictBool] = Field(default=None, description="Whether this run copied poster thumbnails")
    enrich_metadata: Optional[StrictBool] = Field(default=None, description="Whether this run backfills omitted source-metadata fields (see the import-level property).")
    __properties: ClassVar[List[str]] = ["object", "id", "import_id", "import_type", "mode", "delete_missing", "status", "progress", "error", "started_at", "completed_at", "created_at", "max_files", "include_thumbnails", "enrich_metadata"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['metadata_import_run']):
            raise ValueError("must be one of enum values ('metadata_import_run')")
        return value

    @field_validator('import_type')
    def import_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['metadata', 'media']):
            raise ValueError("must be one of enum values ('metadata', 'media')")
        return value

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['append', 'refresh']):
            raise ValueError("must be one of enum values ('append', 'refresh')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending', 'processing', 'completed', 'failed', 'cancelled']):
            raise ValueError("must be one of enum values ('pending', 'processing', 'completed', 'failed', 'cancelled')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MetadataImportRun from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of progress
        if self.progress:
            _dict['progress'] = self.progress.to_dict()
        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['started_at'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        # set to None if max_files (nullable) is None
        # and model_fields_set contains the field
        if self.max_files is None and "max_files" in self.model_fields_set:
            _dict['max_files'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MetadataImportRun from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object"),
            "id": obj.get("id"),
            "import_id": obj.get("import_id"),
            "import_type": obj.get("import_type"),
            "mode": obj.get("mode"),
            "delete_missing": obj.get("delete_missing"),
            "status": obj.get("status"),
            "progress": MetadataImportRunProgress.from_dict(obj["progress"]) if obj.get("progress") is not None else None,
            "error": obj.get("error"),
            "started_at": obj.get("started_at"),
            "completed_at": obj.get("completed_at"),
            "created_at": obj.get("created_at"),
            "max_files": obj.get("max_files"),
            "include_thumbnails": obj.get("include_thumbnails"),
            "enrich_metadata": obj.get("enrich_metadata")
        })
        return _obj


