# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MetadataImportFilterSet(BaseModel):
    """
    One listing pass over the connector's source — the same query params as GET /data-connectors/{id}/files. Which keys a connector honors is validated at import creation (an unsupported key is rejected with a 400, never silently dropped): google-drive supports from/to/title_search/folder_id; dropbox from/to/title_search/path/recursive; zoom and gong from/to/title_search; grain from/to/title_search/team/meeting_type; recall from/to; iconik from/to/title_search. Zoom and Gong listings default to a 6-month lookback when no `from` is given; creation pins that date into the stored filters (six months before the set's `to` when one is given, else before creation time) so every run lists the same stable window — pass an explicit `from` to control the window yourself. iconik listings automatically window by date past iconik's 10,000-result search cap, so a single unfiltered set can cover any source size; only the degenerate case of 10,000+ assets sharing one creation timestamp still requires splitting into multiple date-window sets.
    """ # noqa: E501
    var_from: Optional[date] = Field(default=None, description="Only include source files from on/after this date (YYYY-MM-DD, UTC)", alias="from")
    to: Optional[date] = Field(default=None, description="Only include source files from on/before this date (YYYY-MM-DD, UTC)")
    folder_id: Optional[StrictStr] = Field(default=None, description="Restrict listing to a folder's direct children (Google Drive only). Omit to list the entire corpus.")
    path: Optional[StrictStr] = Field(default=None, description="Restrict listing to a folder path (Dropbox only). Dropbox listing is non-recursive: an import ingests only the direct children of this path (or of the root when omitted — typically all folders, i.e. nothing). Use one filter set per folder to cover a tree.")
    title_search: Optional[StrictStr] = Field(default=None, description="Only include files whose title matches this search")
    team: Optional[StrictStr] = Field(default=None, description="Restrict to a team (Grain only)")
    meeting_type: Optional[StrictStr] = Field(default=None, description="Restrict to a meeting type (Grain only)")
    recursive: Optional[StrictStr] = Field(default=None, description="Dropbox only: 'true' imports the whole subtree under `path` (or the whole account when no `path` is given) instead of direct children.")
    __properties: ClassVar[List[str]] = ["from", "to", "folder_id", "path", "title_search", "team", "meeting_type", "recursive"]

    @field_validator('recursive')
    def recursive_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['true', 'false']):
            raise ValueError("must be one of enum values ('true', 'false')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MetadataImportFilterSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MetadataImportFilterSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "from": obj.get("from"),
            "to": obj.get("to"),
            "folder_id": obj.get("folder_id"),
            "path": obj.get("path"),
            "title_search": obj.get("title_search"),
            "team": obj.get("team"),
            "meeting_type": obj.get("meeting_type"),
            "recursive": obj.get("recursive")
        })
        return _obj


