# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MetadataImportRunProgress(BaseModel):
    """
    Best-effort progress counters for display. Run completion is decided from the actual per-file indexing state, never from these counters, so they can drift slightly under retries without affecting correctness.
    """ # noqa: E501
    pages_listed: Optional[StrictInt] = Field(default=None, description="Connector list pages fetched")
    files_listed: Optional[StrictInt] = Field(default=None, description="Source files seen across all filter sets")
    files_created: Optional[StrictInt] = Field(default=None, description="New Cloudglue files created")
    files_updated: Optional[StrictInt] = Field(default=None, description="Existing files re-imported (refresh mode)")
    files_skipped: Optional[StrictInt] = Field(default=None, description="Already-imported files left untouched (append mode)")
    files_failed: Optional[StrictInt] = Field(default=None, description="Files whose metadata indexing failed")
    files_queued: Optional[StrictInt] = Field(default=None, description="Files handed to indexing — the denominator for progress (indexed + failed settle against it)")
    files_indexed: Optional[StrictInt] = Field(default=None, description="Files whose metadata finished indexing (metadata imports)")
    files_imported: Optional[StrictInt] = Field(default=None, description="Files whose media was ingested and added to the collection (media imports)")
    files_removed: Optional[StrictInt] = Field(default=None, description="Files removed by the delete-missing sweep")
    files_enriched: Optional[StrictInt] = Field(default=None, description="Files whose source_metadata an enrichment batch backfilled (enrich_metadata runs only).")
    __properties: ClassVar[List[str]] = ["pages_listed", "files_listed", "files_created", "files_updated", "files_skipped", "files_failed", "files_queued", "files_indexed", "files_imported", "files_removed", "files_enriched"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MetadataImportRunProgress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MetadataImportRunProgress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pages_listed": obj.get("pages_listed"),
            "files_listed": obj.get("files_listed"),
            "files_created": obj.get("files_created"),
            "files_updated": obj.get("files_updated"),
            "files_skipped": obj.get("files_skipped"),
            "files_failed": obj.get("files_failed"),
            "files_queued": obj.get("files_queued"),
            "files_indexed": obj.get("files_indexed"),
            "files_imported": obj.get("files_imported"),
            "files_removed": obj.get("files_removed"),
            "files_enriched": obj.get("files_enriched")
        })
        return _obj


