# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.17
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from cloudglue.sdk.models.metadata_import_filter_set import MetadataImportFilterSet
from cloudglue.sdk.models.metadata_import_run import MetadataImportRun
from typing import Optional, Set
from typing_extensions import Self

class MetadataImportDetail(BaseModel):
    """
    A metadata import with one page of its run history (newest first). total_runs/limit/offset make truncation visible.
    """ # noqa: E501
    object: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    collection_id: Optional[StrictStr] = None
    connector_id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    filters: Optional[List[MetadataImportFilterSet]] = None
    default_mode: Optional[StrictStr] = None
    delete_missing: Optional[StrictBool] = None
    rate_limit: Optional[StrictInt] = Field(default=None, description="Upstream list requests per second; null means the per-connector safe default. Clamped to a per-connector ceiling at run time.")
    created_at: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Unix timestamp in milliseconds")
    runs: Optional[List[MetadataImportRun]] = Field(default=None, description="One page of run history, newest first")
    total_runs: Optional[StrictInt] = None
    limit: Optional[StrictInt] = None
    offset: Optional[StrictInt] = None
    max_files: Optional[StrictInt] = Field(default=None, description="Per-run ceiling on files processed from the listing; null means unbounded")
    include_thumbnails: Optional[StrictBool] = Field(default=None, description="Whether runs copy connector poster images as default thumbnails for imported files (Grain and iconik today)")
    __properties: ClassVar[List[str]] = ["object", "id", "collection_id", "connector_id", "name", "filters", "default_mode", "delete_missing", "rate_limit", "created_at", "runs", "total_runs", "limit", "offset", "max_files", "include_thumbnails"]

    @field_validator('object')
    def object_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['metadata_import']):
            raise ValueError("must be one of enum values ('metadata_import')")
        return value

    @field_validator('default_mode')
    def default_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['append', 'refresh']):
            raise ValueError("must be one of enum values ('append', 'refresh')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MetadataImportDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in filters (list)
        _items = []
        if self.filters:
            for _item_filters in self.filters:
                if _item_filters:
                    _items.append(_item_filters.to_dict())
            _dict['filters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in runs (list)
        _items = []
        if self.runs:
            for _item_runs in self.runs:
                if _item_runs:
                    _items.append(_item_runs.to_dict())
            _dict['runs'] = _items
        # set to None if rate_limit (nullable) is None
        # and model_fields_set contains the field
        if self.rate_limit is None and "rate_limit" in self.model_fields_set:
            _dict['rate_limit'] = None

        # set to None if max_files (nullable) is None
        # and model_fields_set contains the field
        if self.max_files is None and "max_files" in self.model_fields_set:
            _dict['max_files'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MetadataImportDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "object": obj.get("object"),
            "id": obj.get("id"),
            "collection_id": obj.get("collection_id"),
            "connector_id": obj.get("connector_id"),
            "name": obj.get("name"),
            "filters": [MetadataImportFilterSet.from_dict(_item) for _item in obj["filters"]] if obj.get("filters") is not None else None,
            "default_mode": obj.get("default_mode"),
            "delete_missing": obj.get("delete_missing"),
            "rate_limit": obj.get("rate_limit"),
            "created_at": obj.get("created_at"),
            "runs": [MetadataImportRun.from_dict(_item) for _item in obj["runs"]] if obj.get("runs") is not None else None,
            "total_runs": obj.get("total_runs"),
            "limit": obj.get("limit"),
            "offset": obj.get("offset"),
            "max_files": obj.get("max_files"),
            "include_thumbnails": obj.get("include_thumbnails")
        })
        return _obj


