# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.30
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cloudglue.sdk.models.moment_criterion_anchors_value import MomentCriterionAnchorsValue
from cloudglue.sdk.models.moment_criterion_scoring import MomentCriterionScoring
from typing import Optional, Set
from typing_extensions import Self

class MomentCriterion(BaseModel):
    """
    An inline criterion: rubric instructions plus typed output declarations. Snapshotted and hashed onto the run.
    """ # noqa: E501
    name: Annotated[str, Field(strict=True, max_length=64)]
    instructions: Annotated[str, Field(min_length=1, strict=True)] = Field(description="The complete rubric, including any seed lists and worked examples.")
    moment_schema: Optional[Dict[str, Any]] = Field(default=None, description="A validated JSON Schema subset (the moment schema dialect): a root object of string/number/integer/boolean/array-of-those fields, optional enums, one nesting level, per-field descriptions. Rejected shapes get a field-addressable 400 with a stable code.")
    finding_schema: Optional[Dict[str, Any]] = Field(default=None, description="A validated JSON Schema subset (the moment schema dialect): a root object of string/number/integer/boolean/array-of-those fields, optional enums, one nesting level, per-field descriptions. Rejected shapes get a field-addressable 400 with a stable code.")
    anchors: Optional[Dict[str, MomentCriterionAnchorsValue]] = Field(default=None, description="Named intra-moment timestamps. A non-required anchor that does not exist is omitted from the moment - never null.")
    scoring: Optional[MomentCriterionScoring] = None
    __properties: ClassVar[List[str]] = ["name", "instructions", "moment_schema", "finding_schema", "anchors", "scoring"]

    @field_validator('name')
    def name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-z][a-z0-9_]*$", value):
            raise ValueError(r"must validate the regular expression /^[a-z][a-z0-9_]*$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MomentCriterion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in anchors (dict)
        _field_dict = {}
        if self.anchors:
            for _key_anchors in self.anchors:
                if self.anchors[_key_anchors]:
                    _field_dict[_key_anchors] = self.anchors[_key_anchors].to_dict()
            _dict['anchors'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of scoring
        if self.scoring:
            _dict['scoring'] = self.scoring.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MomentCriterion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "instructions": obj.get("instructions"),
            "moment_schema": obj.get("moment_schema"),
            "finding_schema": obj.get("finding_schema"),
            "anchors": dict(
                (_k, MomentCriterionAnchorsValue.from_dict(_v))
                for _k, _v in obj["anchors"].items()
            )
            if obj.get("anchors") is not None
            else None,
            "scoring": MomentCriterionScoring.from_dict(obj["scoring"]) if obj.get("scoring") is not None else None
        })
        return _obj


