# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.32
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from cloudglue.sdk.models.moment_criterion import MomentCriterion
from cloudglue.sdk.models.new_find_moments_speaker_filter import NewFindMomentsSpeakerFilter
from typing import Optional, Set
from typing_extensions import Self

class NewFindMoments(BaseModel):
    """
    NewFindMoments
    """ # noqa: E501
    url: StrictStr = Field(description="cloudglue://files/<id> or an ingestible URL (same resolution rules as describe/extract).")
    describe_job_id: Optional[StrictStr] = Field(default=None, description="Optional pin to a specific describe. It must exist for the file and its config must cover signals_required.")
    criterion: MomentCriterion
    signals_required: Optional[Annotated[List[StrictStr], Field(min_length=1)]] = None
    boundary_policy: Optional[StrictStr] = 'sentence'
    speaker_filter: Optional[NewFindMomentsSpeakerFilter] = None
    min_duration_seconds: Optional[Union[Annotated[float, Field(strict=True, gt=0)], Annotated[int, Field(strict=True, gt=0)]]] = 5
    max_duration_seconds: Optional[Union[Annotated[float, Field(strict=True, gt=0)], Annotated[int, Field(strict=True, gt=0)]]] = 300
    cache_policy: Optional[StrictStr] = 'reuse'
    __properties: ClassVar[List[str]] = ["url", "describe_job_id", "criterion", "signals_required", "boundary_policy", "speaker_filter", "min_duration_seconds", "max_duration_seconds", "cache_policy"]

    @field_validator('signals_required')
    def signals_required_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['speech', 'visual_scene_description', 'scene_text', 'audio_description']):
                raise ValueError("each list item must be one of ('speech', 'visual_scene_description', 'scene_text', 'audio_description')")
        return value

    @field_validator('boundary_policy')
    def boundary_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['sentence', 'tight', 'loose']):
            raise ValueError("must be one of enum values ('sentence', 'tight', 'loose')")
        return value

    @field_validator('cache_policy')
    def cache_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['reuse', 'refresh']):
            raise ValueError("must be one of enum values ('reuse', 'refresh')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NewFindMoments from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of criterion
        if self.criterion:
            _dict['criterion'] = self.criterion.to_dict()
        # override the default output from pydantic by calling `to_dict()` of speaker_filter
        if self.speaker_filter:
            _dict['speaker_filter'] = self.speaker_filter.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NewFindMoments from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "describe_job_id": obj.get("describe_job_id"),
            "criterion": MomentCriterion.from_dict(obj["criterion"]) if obj.get("criterion") is not None else None,
            "signals_required": obj.get("signals_required"),
            "boundary_policy": obj.get("boundary_policy") if obj.get("boundary_policy") is not None else 'sentence',
            "speaker_filter": NewFindMomentsSpeakerFilter.from_dict(obj["speaker_filter"]) if obj.get("speaker_filter") is not None else None,
            "min_duration_seconds": obj.get("min_duration_seconds") if obj.get("min_duration_seconds") is not None else 5,
            "max_duration_seconds": obj.get("max_duration_seconds") if obj.get("max_duration_seconds") is not None else 300,
            "cache_policy": obj.get("cache_policy") if obj.get("cache_policy") is not None else 'reuse'
        })
        return _obj


