# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class QueryUsage(BaseModel):
    """
    QueryUsage
    """ # noqa: E501
    files_scanned: Optional[StrictInt] = Field(default=None, description="Number of files loaded into the files virtual table")
    entity_rows: Optional[StrictInt] = Field(default=None, description="Number of rows loaded into the entities virtual table")
    segment_entity_rows: Optional[StrictInt] = Field(default=None, description="Number of rows loaded into the segment_entities virtual table")
    engine_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="SQL execution time in milliseconds")
    total_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Total processing time in milliseconds, including dataset preparation")
    __properties: ClassVar[List[str]] = ["files_scanned", "entity_rows", "segment_entity_rows", "engine_ms", "total_ms"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QueryUsage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QueryUsage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "files_scanned": obj.get("files_scanned"),
            "entity_rows": obj.get("entity_rows"),
            "segment_entity_rows": obj.get("segment_entity_rows"),
            "engine_ms": obj.get("engine_ms"),
            "total_ms": obj.get("total_ms")
        })
        return _obj


