# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.12
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RecallSourceMetadata(BaseModel):
    """
    Source provenance captured from Recall at ingest time. Artifact availability is exposed as booleans — signed artifact download URLs are never included.
    """ # noqa: E501
    source_type: StrictStr = Field(description="Discriminator identifying the upstream connector.")
    recall_recording_id: StrictStr = Field(description="Recall recording id.")
    created_at: Optional[StrictStr] = Field(default=None, description="UTC time the recording object was created.")
    started_at: Optional[StrictStr] = Field(default=None, description="UTC time recording started.")
    completed_at: Optional[StrictStr] = Field(default=None, description="UTC time recording completed.")
    expires_at: Optional[StrictStr] = Field(default=None, description="UTC time the recording expires upstream at Recall.")
    status_code: Optional[StrictStr] = Field(default=None, description="Recall status: done, processing, failed, or paused. Only done recordings can be synced.")
    meeting_title: Optional[StrictStr] = Field(default=None, description="Meeting title, when Recall's meeting metadata carries one.")
    meeting_platform: Optional[StrictStr] = Field(default=None, description="Meeting platform (e.g. zoom, google_meet), when available.")
    has_transcript: Optional[StrictBool] = Field(default=None, description="Whether a transcript artifact exists.")
    has_audio: Optional[StrictBool] = Field(default=None, description="Whether a separate audio artifact exists.")
    has_participant_events: Optional[StrictBool] = Field(default=None, description="Whether a participant-events artifact exists.")
    bot_id: Optional[StrictStr] = Field(default=None, description="Id of the bot that captured the recording.")
    recall_metadata: Optional[Dict[str, Any]] = Field(default=None, description="Arbitrary caller-supplied metadata attached to the bot/recording in Recall.")
    __properties: ClassVar[List[str]] = ["source_type", "recall_recording_id", "created_at", "started_at", "completed_at", "expires_at", "status_code", "meeting_title", "meeting_platform", "has_transcript", "has_audio", "has_participant_events", "bot_id", "recall_metadata"]

    @field_validator('source_type')
    def source_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['recall']):
            raise ValueError("must be one of enum values ('recall')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecallSourceMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['started_at'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expires_at'] = None

        # set to None if status_code (nullable) is None
        # and model_fields_set contains the field
        if self.status_code is None and "status_code" in self.model_fields_set:
            _dict['status_code'] = None

        # set to None if meeting_title (nullable) is None
        # and model_fields_set contains the field
        if self.meeting_title is None and "meeting_title" in self.model_fields_set:
            _dict['meeting_title'] = None

        # set to None if meeting_platform (nullable) is None
        # and model_fields_set contains the field
        if self.meeting_platform is None and "meeting_platform" in self.model_fields_set:
            _dict['meeting_platform'] = None

        # set to None if has_transcript (nullable) is None
        # and model_fields_set contains the field
        if self.has_transcript is None and "has_transcript" in self.model_fields_set:
            _dict['has_transcript'] = None

        # set to None if has_audio (nullable) is None
        # and model_fields_set contains the field
        if self.has_audio is None and "has_audio" in self.model_fields_set:
            _dict['has_audio'] = None

        # set to None if has_participant_events (nullable) is None
        # and model_fields_set contains the field
        if self.has_participant_events is None and "has_participant_events" in self.model_fields_set:
            _dict['has_participant_events'] = None

        # set to None if bot_id (nullable) is None
        # and model_fields_set contains the field
        if self.bot_id is None and "bot_id" in self.model_fields_set:
            _dict['bot_id'] = None

        # set to None if recall_metadata (nullable) is None
        # and model_fields_set contains the field
        if self.recall_metadata is None and "recall_metadata" in self.model_fields_set:
            _dict['recall_metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecallSourceMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source_type": obj.get("source_type"),
            "recall_recording_id": obj.get("recall_recording_id"),
            "created_at": obj.get("created_at"),
            "started_at": obj.get("started_at"),
            "completed_at": obj.get("completed_at"),
            "expires_at": obj.get("expires_at"),
            "status_code": obj.get("status_code"),
            "meeting_title": obj.get("meeting_title"),
            "meeting_platform": obj.get("meeting_platform"),
            "has_transcript": obj.get("has_transcript"),
            "has_audio": obj.get("has_audio"),
            "has_participant_events": obj.get("has_participant_events"),
            "bot_id": obj.get("bot_id"),
            "recall_metadata": obj.get("recall_metadata")
        })
        return _obj


