# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.15
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ResponseQueryCall(BaseModel):
    """
    A read-only SQL query the nimbus-002 agent ran over the structured (extracted) data. Result rows are not included in v1.
    """ # noqa: E501
    type: Optional[StrictStr] = Field(default=None, description="The type of output item")
    id: Optional[StrictStr] = Field(default=None, description="Identifier for this query call (query_<toolCallId>)")
    status: Optional[StrictStr] = Field(default=None, description="Whether the query executed successfully")
    sql: Optional[StrictStr] = Field(default=None, description="The SQL SELECT that was executed")
    row_count: Optional[StrictInt] = Field(default=None, description="Rows returned to the model after truncation")
    total_rows: Optional[StrictInt] = Field(default=None, description="True total when the engine saw the whole result; null when truncated")
    truncated: Optional[StrictBool] = Field(default=None, description="Whether the result was truncated (row or byte cap) before reaching the model")
    error: Optional[StrictStr] = Field(default=None, description="Error message when status is failed; null otherwise")
    __properties: ClassVar[List[str]] = ["type", "id", "status", "sql", "row_count", "total_rows", "truncated", "error"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['cloudglue_query_call']):
            raise ValueError("must be one of enum values ('cloudglue_query_call')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['completed', 'failed']):
            raise ValueError("must be one of enum values ('completed', 'failed')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResponseQueryCall from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if total_rows (nullable) is None
        # and model_fields_set contains the field
        if self.total_rows is None and "total_rows" in self.model_fields_set:
            _dict['total_rows'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResponseQueryCall from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "id": obj.get("id"),
            "status": obj.get("status"),
            "sql": obj.get("sql"),
            "row_count": obj.get("row_count"),
            "total_rows": obj.get("total_rows"),
            "truncated": obj.get("truncated"),
            "error": obj.get("error")
        })
        return _obj


