# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class SiteRoutePreview(BaseModel):
    """
    SiteRoutePreview
    """ # noqa: E501
    id: StrictStr
    route: Annotated[str, Field(strict=True, max_length=512)] = Field(description="The site route this preview applies to. Stored and matched in canonical form: hash-router prefixes ('#/'), query strings, and surrounding slashes are stripped, so '/clip/intro', 'clip/intro/', and '#/clip/intro' all name the same route. Must not be empty after canonicalization — the site root unfurls with the site-level preview fields.")
    preview_title: Optional[StrictStr] = Field(default=None, description="Preview card title. Falls back to the hero share's own title (then its filename) when unset.", alias="previewTitle")
    preview_description: Optional[Annotated[str, Field(strict=True, max_length=1000)]] = Field(default=None, description="Preview card description. Falls back to the hero share's own description when unset. Slack truncates at 200 characters.", alias="previewDescription")
    preview_image_url: Optional[StrictStr] = Field(default=None, description="Preview card image. Must be a publicly fetchable URL (e.g. a share's preview_url) — site asset URLs sit behind the private-site gate and won't render. Falls back to the hero share's thumbnail when unset.", alias="previewImageUrl")
    preview_share_id: StrictStr = Field(description="The route's hero share: what a link to this page plays when unfurled by the Cloudglue Slack app. Must be a video share owned by the same account; on a public site it must be a public share.", alias="previewShareId")
    start_seconds: Optional[Union[Annotated[float, Field(strict=True, ge=0)], Annotated[int, Field(strict=True, ge=0)]]] = Field(default=None, description="Clip window start, in seconds (fractional allowed). Requires endSeconds; the unfurled player then plays only the [startSeconds, endSeconds] window of the hero share. Precision note: the stream is trimmed with Mux instant clipping, which cuts at the asset's HLS segment boundaries (start rounds down, end rounds up) — not frame-accurate, so the served clip can include a few extra seconds on either side depending on the asset's segment length.", alias="startSeconds")
    end_seconds: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Clip window end, in seconds (fractional allowed). Requires startSeconds and must be greater than it. Served at HLS segment granularity — see startSeconds.", alias="endSeconds")
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "route", "previewTitle", "previewDescription", "previewImageUrl", "previewShareId", "startSeconds", "endSeconds", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SiteRoutePreview from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if preview_title (nullable) is None
        # and model_fields_set contains the field
        if self.preview_title is None and "preview_title" in self.model_fields_set:
            _dict['previewTitle'] = None

        # set to None if preview_description (nullable) is None
        # and model_fields_set contains the field
        if self.preview_description is None and "preview_description" in self.model_fields_set:
            _dict['previewDescription'] = None

        # set to None if preview_image_url (nullable) is None
        # and model_fields_set contains the field
        if self.preview_image_url is None and "preview_image_url" in self.model_fields_set:
            _dict['previewImageUrl'] = None

        # set to None if start_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.start_seconds is None and "start_seconds" in self.model_fields_set:
            _dict['startSeconds'] = None

        # set to None if end_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.end_seconds is None and "end_seconds" in self.model_fields_set:
            _dict['endSeconds'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SiteRoutePreview from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "route": obj.get("route"),
            "previewTitle": obj.get("previewTitle"),
            "previewDescription": obj.get("previewDescription"),
            "previewImageUrl": obj.get("previewImageUrl"),
            "previewShareId": obj.get("previewShareId"),
            "startSeconds": obj.get("startSeconds"),
            "endSeconds": obj.get("endSeconds"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


