# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.11
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from cloudglue.sdk.models.dropbox_source_metadata import DropboxSourceMetadata
from cloudglue.sdk.models.gong_source_metadata import GongSourceMetadata
from cloudglue.sdk.models.google_drive_source_metadata import GoogleDriveSourceMetadata
from cloudglue.sdk.models.grain_source_metadata import GrainSourceMetadata
from cloudglue.sdk.models.iconik_source_metadata import IconikSourceMetadata
from cloudglue.sdk.models.recall_source_metadata import RecallSourceMetadata
from cloudglue.sdk.models.zoom_source_metadata import ZoomSourceMetadata
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

SOURCEMETADATA_ONE_OF_SCHEMAS = ["DropboxSourceMetadata", "GongSourceMetadata", "GoogleDriveSourceMetadata", "GrainSourceMetadata", "IconikSourceMetadata", "RecallSourceMetadata", "ZoomSourceMetadata"]

class SourceMetadata(BaseModel):
    """
    Per-source provenance captured from the upstream connector, discriminated by source_type. Populated for Grain, Zoom, Recall, Google Drive, Dropbox, Gong, and iconik; files synced before a connector was upgraded carry null. S3/GCS files carry null (plain object stores have no richer metadata).
    """
    # data type: GrainSourceMetadata
    oneof_schema_1_validator: Optional[GrainSourceMetadata] = None
    # data type: ZoomSourceMetadata
    oneof_schema_2_validator: Optional[ZoomSourceMetadata] = None
    # data type: RecallSourceMetadata
    oneof_schema_3_validator: Optional[RecallSourceMetadata] = None
    # data type: GoogleDriveSourceMetadata
    oneof_schema_4_validator: Optional[GoogleDriveSourceMetadata] = None
    # data type: DropboxSourceMetadata
    oneof_schema_5_validator: Optional[DropboxSourceMetadata] = None
    # data type: GongSourceMetadata
    oneof_schema_6_validator: Optional[GongSourceMetadata] = None
    # data type: IconikSourceMetadata
    oneof_schema_7_validator: Optional[IconikSourceMetadata] = None
    actual_instance: Optional[Union[DropboxSourceMetadata, GongSourceMetadata, GoogleDriveSourceMetadata, GrainSourceMetadata, IconikSourceMetadata, RecallSourceMetadata, ZoomSourceMetadata]] = None
    one_of_schemas: Set[str] = { "DropboxSourceMetadata", "GongSourceMetadata", "GoogleDriveSourceMetadata", "GrainSourceMetadata", "IconikSourceMetadata", "RecallSourceMetadata", "ZoomSourceMetadata" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = SourceMetadata.model_construct()
        error_messages = []
        match = 0
        # validate data type: GrainSourceMetadata
        if not isinstance(v, GrainSourceMetadata):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GrainSourceMetadata`")
        else:
            match += 1
        # validate data type: ZoomSourceMetadata
        if not isinstance(v, ZoomSourceMetadata):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ZoomSourceMetadata`")
        else:
            match += 1
        # validate data type: RecallSourceMetadata
        if not isinstance(v, RecallSourceMetadata):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RecallSourceMetadata`")
        else:
            match += 1
        # validate data type: GoogleDriveSourceMetadata
        if not isinstance(v, GoogleDriveSourceMetadata):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GoogleDriveSourceMetadata`")
        else:
            match += 1
        # validate data type: DropboxSourceMetadata
        if not isinstance(v, DropboxSourceMetadata):
            error_messages.append(f"Error! Input type `{type(v)}` is not `DropboxSourceMetadata`")
        else:
            match += 1
        # validate data type: GongSourceMetadata
        if not isinstance(v, GongSourceMetadata):
            error_messages.append(f"Error! Input type `{type(v)}` is not `GongSourceMetadata`")
        else:
            match += 1
        # validate data type: IconikSourceMetadata
        if not isinstance(v, IconikSourceMetadata):
            error_messages.append(f"Error! Input type `{type(v)}` is not `IconikSourceMetadata`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in SourceMetadata with oneOf schemas: DropboxSourceMetadata, GongSourceMetadata, GoogleDriveSourceMetadata, GrainSourceMetadata, IconikSourceMetadata, RecallSourceMetadata, ZoomSourceMetadata. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in SourceMetadata with oneOf schemas: DropboxSourceMetadata, GongSourceMetadata, GoogleDriveSourceMetadata, GrainSourceMetadata, IconikSourceMetadata, RecallSourceMetadata, ZoomSourceMetadata. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into GrainSourceMetadata
        try:
            instance.actual_instance = GrainSourceMetadata.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ZoomSourceMetadata
        try:
            instance.actual_instance = ZoomSourceMetadata.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RecallSourceMetadata
        try:
            instance.actual_instance = RecallSourceMetadata.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GoogleDriveSourceMetadata
        try:
            instance.actual_instance = GoogleDriveSourceMetadata.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DropboxSourceMetadata
        try:
            instance.actual_instance = DropboxSourceMetadata.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into GongSourceMetadata
        try:
            instance.actual_instance = GongSourceMetadata.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into IconikSourceMetadata
        try:
            instance.actual_instance = IconikSourceMetadata.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into SourceMetadata with oneOf schemas: DropboxSourceMetadata, GongSourceMetadata, GoogleDriveSourceMetadata, GrainSourceMetadata, IconikSourceMetadata, RecallSourceMetadata, ZoomSourceMetadata. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into SourceMetadata with oneOf schemas: DropboxSourceMetadata, GongSourceMetadata, GoogleDriveSourceMetadata, GrainSourceMetadata, IconikSourceMetadata, RecallSourceMetadata, ZoomSourceMetadata. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], DropboxSourceMetadata, GongSourceMetadata, GoogleDriveSourceMetadata, GrainSourceMetadata, IconikSourceMetadata, RecallSourceMetadata, ZoomSourceMetadata]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


