# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.6.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from cloudglue.sdk.models.word_timestamp import WordTimestamp
from typing import Optional, Set
from typing_extensions import Self

class SpeechOutputPart(BaseModel):
    """
    SpeechOutputPart
    """ # noqa: E501
    speaker: Optional[StrictStr] = Field(default=None, description="Identified speaker")
    text: Optional[StrictStr] = Field(default=None, description="Transcribed speech text")
    start_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Start time of speech in seconds")
    end_time: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="End time of speech in seconds")
    words: Optional[List[WordTimestamp]] = Field(default=None, description="Word-level timestamps. Only present when include_word_timestamps=true. Not available for YouTube sources.")
    __properties: ClassVar[List[str]] = ["speaker", "text", "start_time", "end_time", "words"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SpeechOutputPart from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in words (list)
        _items = []
        if self.words:
            for _item_words in self.words:
                if _item_words:
                    _items.append(_item_words.to_dict())
            _dict['words'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SpeechOutputPart from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "speaker": obj.get("speaker"),
            "text": obj.get("text"),
            "start_time": obj.get("start_time"),
            "end_time": obj.get("end_time"),
            "words": [WordTimestamp.from_dict(_item) for _item in obj["words"]] if obj.get("words") is not None else None
        })
        return _obj


