# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ZoomSourceMetadataRecordingFilesInner(BaseModel):
    """
    ZoomSourceMetadataRecordingFilesInner
    """ # noqa: E501
    id: Optional[StrictStr] = None
    recording_type: Optional[StrictStr] = Field(default=None, description="e.g. shared_screen_with_speaker_view, audio_only.")
    file_type: Optional[StrictStr] = None
    file_extension: Optional[StrictStr] = None
    file_size: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="File size in bytes.")
    recording_start: Optional[StrictStr] = None
    recording_end: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "recording_type", "file_type", "file_extension", "file_size", "recording_start", "recording_end", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ZoomSourceMetadataRecordingFilesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if recording_type (nullable) is None
        # and model_fields_set contains the field
        if self.recording_type is None and "recording_type" in self.model_fields_set:
            _dict['recording_type'] = None

        # set to None if file_type (nullable) is None
        # and model_fields_set contains the field
        if self.file_type is None and "file_type" in self.model_fields_set:
            _dict['file_type'] = None

        # set to None if file_extension (nullable) is None
        # and model_fields_set contains the field
        if self.file_extension is None and "file_extension" in self.model_fields_set:
            _dict['file_extension'] = None

        # set to None if file_size (nullable) is None
        # and model_fields_set contains the field
        if self.file_size is None and "file_size" in self.model_fields_set:
            _dict['file_size'] = None

        # set to None if recording_start (nullable) is None
        # and model_fields_set contains the field
        if self.recording_start is None and "recording_start" in self.model_fields_set:
            _dict['recording_start'] = None

        # set to None if recording_end (nullable) is None
        # and model_fields_set contains the field
        if self.recording_end is None and "recording_end" in self.model_fields_set:
            _dict['recording_end'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ZoomSourceMetadataRecordingFilesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "recording_type": obj.get("recording_type"),
            "file_type": obj.get("file_type"),
            "file_extension": obj.get("file_extension"),
            "file_size": obj.get("file_size"),
            "recording_start": obj.get("recording_start"),
            "recording_end": obj.get("recording_end"),
            "status": obj.get("status")
        })
        return _obj


