# coding: utf-8

"""
    Cloudglue API

    API for Cloudglue

    The version of the OpenAPI document: 0.7.12
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from cloudglue.sdk.models.zoom_source_metadata_recording_files_inner import ZoomSourceMetadataRecordingFilesInner
from typing import Optional, Set
from typing_extensions import Self

class ZoomSourceMetadata(BaseModel):
    """
    Source provenance captured from Zoom at ingest time. Signed download/play URLs, share URLs, and passcodes are never included.
    """ # noqa: E501
    source_type: StrictStr = Field(description="Discriminator identifying the upstream connector.")
    zoom_meeting_uuid: StrictStr = Field(description="Zoom meeting instance UUID.")
    zoom_meeting_id: Optional[StrictInt] = Field(default=None, description="Zoom numeric meeting id.")
    topic: Optional[StrictStr] = Field(default=None, description="Meeting topic (empty string when Zoom omits it).")
    start_time: Optional[datetime] = Field(default=None, description="UTC time the meeting started.")
    host_id: Optional[StrictStr] = Field(default=None, description="Zoom host user id.")
    host_email: Optional[StrictStr] = Field(default=None, description="Host email. Nullable whenever Zoom omits it — both list and per-meeting endpoints may return null depending on account scopes.")
    account_id: Optional[StrictStr] = Field(default=None, description="Zoom account id.")
    timezone: Optional[StrictStr] = Field(default=None, description="Meeting timezone.")
    duration_minutes: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Meeting duration in minutes (as reported by Zoom).")
    total_size: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Total size of all recording files in bytes.")
    recording_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number of recording files for the meeting.")
    meeting_type: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Zoom's numeric meeting type.")
    recording_files: Optional[List[ZoomSourceMetadataRecordingFilesInner]] = Field(default=None, description="Structural facts about each recording file. Download/play URLs are excluded.")
    __properties: ClassVar[List[str]] = ["source_type", "zoom_meeting_uuid", "zoom_meeting_id", "topic", "start_time", "host_id", "host_email", "account_id", "timezone", "duration_minutes", "total_size", "recording_count", "meeting_type", "recording_files"]

    @field_validator('source_type')
    def source_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['zoom']):
            raise ValueError("must be one of enum values ('zoom')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ZoomSourceMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in recording_files (list)
        _items = []
        if self.recording_files:
            for _item_recording_files in self.recording_files:
                if _item_recording_files:
                    _items.append(_item_recording_files.to_dict())
            _dict['recording_files'] = _items
        # set to None if zoom_meeting_id (nullable) is None
        # and model_fields_set contains the field
        if self.zoom_meeting_id is None and "zoom_meeting_id" in self.model_fields_set:
            _dict['zoom_meeting_id'] = None

        # set to None if topic (nullable) is None
        # and model_fields_set contains the field
        if self.topic is None and "topic" in self.model_fields_set:
            _dict['topic'] = None

        # set to None if start_time (nullable) is None
        # and model_fields_set contains the field
        if self.start_time is None and "start_time" in self.model_fields_set:
            _dict['start_time'] = None

        # set to None if host_id (nullable) is None
        # and model_fields_set contains the field
        if self.host_id is None and "host_id" in self.model_fields_set:
            _dict['host_id'] = None

        # set to None if host_email (nullable) is None
        # and model_fields_set contains the field
        if self.host_email is None and "host_email" in self.model_fields_set:
            _dict['host_email'] = None

        # set to None if account_id (nullable) is None
        # and model_fields_set contains the field
        if self.account_id is None and "account_id" in self.model_fields_set:
            _dict['account_id'] = None

        # set to None if timezone (nullable) is None
        # and model_fields_set contains the field
        if self.timezone is None and "timezone" in self.model_fields_set:
            _dict['timezone'] = None

        # set to None if duration_minutes (nullable) is None
        # and model_fields_set contains the field
        if self.duration_minutes is None and "duration_minutes" in self.model_fields_set:
            _dict['duration_minutes'] = None

        # set to None if total_size (nullable) is None
        # and model_fields_set contains the field
        if self.total_size is None and "total_size" in self.model_fields_set:
            _dict['total_size'] = None

        # set to None if recording_count (nullable) is None
        # and model_fields_set contains the field
        if self.recording_count is None and "recording_count" in self.model_fields_set:
            _dict['recording_count'] = None

        # set to None if meeting_type (nullable) is None
        # and model_fields_set contains the field
        if self.meeting_type is None and "meeting_type" in self.model_fields_set:
            _dict['meeting_type'] = None

        # set to None if recording_files (nullable) is None
        # and model_fields_set contains the field
        if self.recording_files is None and "recording_files" in self.model_fields_set:
            _dict['recording_files'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ZoomSourceMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source_type": obj.get("source_type"),
            "zoom_meeting_uuid": obj.get("zoom_meeting_uuid"),
            "zoom_meeting_id": obj.get("zoom_meeting_id"),
            "topic": obj.get("topic"),
            "start_time": obj.get("start_time"),
            "host_id": obj.get("host_id"),
            "host_email": obj.get("host_email"),
            "account_id": obj.get("account_id"),
            "timezone": obj.get("timezone"),
            "duration_minutes": obj.get("duration_minutes"),
            "total_size": obj.get("total_size"),
            "recording_count": obj.get("recording_count"),
            "meeting_type": obj.get("meeting_type"),
            "recording_files": [ZoomSourceMetadataRecordingFilesInner.from_dict(_item) for _item in obj["recording_files"]] if obj.get("recording_files") is not None else None
        })
        return _obj


